#!/bin/bash

# STEP 1: Install LVM tools
sudo apt update -y
sudo apt install lvm2 -y

# STEP 2: Create Physical Volumes (PVs)
sudo pvcreate /dev/sdb /dev/sdc

# STEP 3: Create Volume Group (VG)
sudo vgcreate vg_data /dev/sdb /dev/sdc

# STEP 4: Create Logical Volume (LV)
sudo lvcreate -L 10G -n lv_app vg_data

# STEP 5: Create filesystem on LV
sudo mkfs.ext4 /dev/vg_data/lv_app

# STEP 6: Create mount point
sudo mkdir -p /mnt/app

# STEP 7: Mount the Logical Volume
sudo mount /dev/vg_data/lv_app /mnt/app

