#!/bin/bash

# STEP 1: Update the system package list
sudo apt update -y

# STEP 2: Install NGINX
sudo apt install nginx -y

# STEP 3: Start the NGINX service
sudo systemctl start nginx

# STEP 4: Enable NGINX on boot
sudo systemctl enable nginx

