#!/bin/bash
# Script Name : install_nginx.sh
# Purpose     : Install and start Nginx on Ubuntu
# OS          : Ubuntu

echo "Updating system packages..."
sudo apt update -y

echo "Installing Nginx..."
sudo apt install nginx -y

echo "Starting Nginx service..."
sudo systemctl start nginx

echo "Enabling Nginx on boot..."
sudo systemctl enable nginx

echo "Checking Nginx status..."
sudo systemctl status nginx --no-pager

echo "Nginx installation completed successfully!"

